src/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

src/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'main'


urlpatterns = [
    path('', views.product_list_page, name='books'),
    path('<slug:slug>/', views.product_list_page, name='books_by_category'),
    path('book/<int:id>/', views.details_page, name='details_of_book'),
    path('author/<slug:slug>/', views.author_page, name='author'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/models.py
from django.db import models
from django.urls import reverse


class Ganre(models.Model):
    name = models.CharField(max_length=63, db_index=True)
    slug = models.SlugField(max_length=63, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Ganre'
        verbose_name_plural = 'Ganres'

    def __str__(self):
        return self.name

class Author(models.Model):
    fullname = models.CharField(max_length=63, db_index=True)
    slug = models.SlugField(max_length=63, unique=True)

    class Meta:
        ordering = ('fullname',)
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse("main:author", args=[self.slug])

class Book(models.Model):
    ganres = models.ManyToManyField(Ganre, related_name='books')
    author = models.ForeignKey(Author, related_name="books", on_delete=models.CASCADE)
    title = models.CharField(max_length=63)
    photo = models.ImageField(upload_to='books/posters/', blank=True)
    desk = models.CharField(max_length=127, blank=True)
    file = models.FileField(upload_to='books/pdfs/')

    def get_absolute_url(self):
        return reverse("main:details_of_book", args=[self.id])

src/main/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Q

from .models import Book, Ganre, Author


def product_list_page(request, slug=None):
    ganres = Ganre.objects.all()
    books = Book.objects.all()
    search = request.GET.get('search')

    ganre = None
    if slug:
        ganre = get_object_or_404(Ganre, slug=slug)
        books = books.filter(ganres=ganre)

    if search:
        books = Book.objects.filter(
            Q(title__icontains=search) |
            Q(author__fullname__icontains=search) |
            Q(ganres__name__icontains=search)
        ).distinct()
    
    context = {
        'ganre': ganre,
        'books': books,
        'ganres': ganres
    }

    return render(request, 'main/list.html', context)

def details_page(request, id):
    book = get_object_or_404(Book, id=id)
    author = book.author
    ganres = Ganre.objects.all()

    context = {
        'book': book,
        'ganres': ganres,
        'author': author
    }

    return render(request, 'main/details.html', context)

def author_page(request, slug):
    author = get_object_or_404(Author, slug=slug)
    ganres = Ganre.objects.all()
    books = author.books.all()

    context = {
        'books': books,
        'ganres': ganres,
        'author': author
    }

    return render(request, 'main/author.html', context)
    

src/main/templates/main/author.html
{% extends 'main/base.html' %}

{% block title %}
    Про Автора
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row" style="margin-bottom: 50px;">
        <h1>{{ author.fullname }}</h1>
    </div>
    <h2>Книги</h2>
    <div class="d-flex flex-wrap justify-content-center p-2" style="gap: 10px;">
        {% for book in books %}
            <div class="card" style="width: 300px;">
                <a href="{{ book.get_absolute_url }}" class="card-img-top" style="height: 400px; width: auto;">
                    <img src="{{ book.photo.url }}" class="w-100 h-100" alt="...">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

src/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main:books' %}"><i class="bi bi-book"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Ganres
                        </a>
                        <ul class="dropdown-menu">
                            {% for ganre in ganres %}
                                <li><a class="dropdown-item" href="/{{ ganre.slug }}">{{ ganre.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

src/main/templates/main/details.html
{% extends "main/base.html" %}

{% block title %}details{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-3">
            <div class="row g-0">
                {% if book.photo %}
                <div class="col-md-4">
                    <img src="{{ book.photo.url }}" class="img-fluid rounded-start" alt="{{ book.title }}">
                </div>
                {% endif %}
                <div class="col-md-8">
                    <div class="card-body">
                        <h2 class="card-title">{{ book.title }}</h2>
                        <p class="card-text">
                            <strong>Автор:</strong>
                            <a href="{{ author.get_absolute_url }}">{{ author.fullname }}</a>
                        </p>
                        <p class="card-text">
                            <strong>Жанри:</strong>
                            {% for genre in book.ganres.all %}
                                <a style="text-decoration: none;" href="/{{ genre.slug }}" class="badge bg-secondary">{{ genre.name }}</a>
                            {% empty %}
                                <span class="text-muted">Немає жанрів</span>
                            {% endfor %}
                        </p>
                        <p>
                            {{ book.desk }}
                        </p>
                        <div class="row text-center aling-items-start">
                            <a href="{% url 'main:books' %}" class="col m-5 btn btn-primary mt-3">Назад до списку книг</a>
                            <a href="{{ book.file.url }}" class="col m-5 btn btn-primary mt-3 gap-5">Скачати</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

src/main/templates/main/list.html
{% extends "main/base.html" %}

{% block title %}Title{% endblock title %}

{% block content %}
    <div class="d-flex flex-wrap justify-content-center p-2" style="gap: 10px;">
        {% for book in books %}
            <div class="card" style="width: 300px;">
                <a href="{{ book.get_absolute_url }}" class="card-img-top" style="height: 400px; width: auto;">
                    <img src="{{ book.photo.url }}" class="w-100 h-100" alt="...">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">{{ book.author }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}